### ISSUE TITLE
Forge 1.20.1 - Crash with Controlling mod

### ISSUE THREAD

**Issue by spunchbop121** [ZedDevStuff/KeybindsPurger#1]
https://mclo.gs/ILcDgCS

The game crashed when I pressed the “purge all keybinds in this category” button

**Comment by ZedDevStuff** [comment]
Fix on the way. For some reason, Controlling doesn't have a refreshEntries method on their keybind list

**Comment by ZedDevStuff** [comment]
Fixed in [1.3.1](https://modrinth.com/mod/keybindspurger/version/1.3.1). Also discovered that the keybinds names didn't update and fixed that too
